name: mady
description: mady users client

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.4
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  injectable: ^1.5.3
  flutter_native_splash: ^2.1.2+1
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  equatable: ^2.0.3
  dartz: ^0.10.1
  http: ^0.13.4
  shared_preferences: ^2.0.13
  connectivity_plus: ^2.2.1
  google_maps_flutter: ^2.1.2
  dropdown_button2: ^1.2.1
  image_picker: ^0.8.4+10
  fancy_bottom_navigation: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  freezed: ^1.1.1
  build_runner: ^2.1.8
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.5
  mockito: ^5.1.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/sale-magenta.png
  color_dark: "#222222"
  image_dark: assets/images/sale-white.png
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/sale-magenta.png
    - assets/images/sale-white.png
  fonts:
    - family: vazir
      fonts:
        - asset: assets/fonts/vazir_regular.ttf
        - asset: assets/fonts/vazir_medium.ttf
          weight: 600
        - asset: assets/fonts/vazir_bold.ttf
          weight: 700